name: OnlySMP
version: '${version}'
main: xyz.fiire.onlysmp.OnlySMP
api-version: 1.18
depend: [ PlaceholderAPI ]
authors: [ FiireWiinter ]
description: Custom Plugin for the Only SMP
website: https://www.fiire.xyz

commands:
  test:
    usage: You can't use this, this is limited to FiireWiinter
    description: FiireWiinter's Test Command
  pay:
    usage: /<command> <player> <amount>
    description: Transfer a player x amount of coins
  withdraw:
    usage: /<command> <amount>
    description: Withdraw a specific amount of coins
  deposit:
    usage: /<command>
    description: Deposit the coins in your hands
  tea:
    usage: /<command>
    description: Fuck you Tea